### ISSUE TITLE
Link to "A Painless Guide to CRC Error Detection Algorithms" is dead

### ISSUE THREAD

**Issue by abrock** [boostorg/crc#10]
The [boost crc.hpp documentation page](https://www.boost.org/doc/libs/1_73_0/libs/crc/crc.html) links to [A Painless Guide to CRC Error Detection Algorithms](http://www.ross.net/crc/crcpaper.html) which is dead. There is a [copy](https://archive.org/stream/PainlessCRC/crc_v3.txt) in the Internet Archive.

ross.net has a [subsite](http://ross.net/home/Cobwebs.html) linking to www.ross.net/crc but that's also dead.

Playing around with urls lead me to find that the "www." is the problem, this link works:

[http://ross.net/crc/download/crc_v3.txt](http://ross.net/crc/download/crc_v3.txt)

**Comment by pdimov** [comment]
http://www.ross.net/crc/crcpaper.html seems to work nowadays.
