### ISSUE TITLE
warning C4800: 'unsigned int': forcing value to bool 'true' or 'false'

### ISSUE THREAD

**Issue by SpareSimian** [boostorg/crc#18]
Visual Studio (2010-2019) report this warning at line 569 in crc.hpp.

            bool const quotient = remainder & high_bit_mask;

Replace with:

            bool const quotient = (remainder & high_bit_mask) != 0;

See also https://lists.boost.org/Archives/boost/2019/04/245932.php

**Comment by SpareSimian** [comment]
Two pull candidates:

https://github.com/boostorg/crc/pull/2
https://github.com/boostorg/crc/pull/7

**Comment by glenfe** [comment]
Should be addressed for 1.80 by 96daae9fcdf965298077ed12a9304ea24713bb40
